### PR TITLE
I've added the ability to have pretty-printed json output in the console when dumping complex data types

### PR DESCRIPTION
**Pull request by MFernstrom**
Add <prettyconsole>true</prettyconsole> under <debugoutput> and you're good to go.
Defaults to standard console output if <prettyconsole> is false or not present.

To use it, just console() things as normal, if it's a complex type and prettyprint is true, it'll parse and pretty-print the data in console.

### CODE REVIEW

**Review by wua22 — COMMENTED** [review]
How about reusing com.naryx.tagfusion.expression.function.string.serializejson.encodeJSON() here to benefit from the logic in there?

**Review by wua22 — COMMENTED** [review]
Also, have a look at ConsoleOutput and how bConsoleOn is set. I think a similar approach with a bConsolePretty would be better than looking up the bluedragon.xml on every execution.

**Comment by MFernstrom** [comment]
Thanks for the feedback!

I'll take a look at that and make a new pull request with the updates

**Comment by MFernstrom** [comment]
@wua22 not a new pull request, but a new commit to this one with the updates.

**Comment by wua22** [comment]
@MFernstrom - the branch has conflicts now apparently.

WRT bConsolePretty, I was actually thinking that the consoleOutput() could be extended to have an optional 2nd argument.  That would take the place of using the bluedragon.xml and is consistent with turning console output on/off.

**Comment by MFernstrom** [comment]
@wua22 - I was going for an engine-wide setting rather than as-needed (Not arguing the point, just explaining why I went this route), I'll extend consoleOutput instead of the kludgy firstRun thing.

Not sure what's up with the conflict though, I'll see if I can untangle the Git unhappiness.

**Comment by MFernstrom** [comment]
@wua22 -  I think that should do it. The setting is now in consoleOutput(), it takes an optional boolean parameter to set pretty print, and I think I sorted the conflict issue.

console( true, true ), console( pretty=true ), console( output=true, pretty=false ), should all work now

**Review by wua22 — APPROVED** [review]
Beautiful!

**Pull request merged**
