### PR TITLE
Bugfix - DateFormat( dt, "short") wasn't returning proper date

### PR DESCRIPTION
**Pull request by MFernstrom**
DateFormat( dt, "short") was returning full length year, I updated so it returns just two digits now, I also updated the MXUnit test helper function so MXUnit doesn't try to run it as a test (And fails)

### CODE REVIEW

**Review by wua22 — APPROVED** [review]
Looks good.

**Comment by wua22** [comment]
I was very curious about this one because I was confident this bug hadn't existed since as long as the "short" mask had existed.

Turns out that it was down to a change in the JDK. Somewhere along the line they decided that "y" should return 4 digits rather than 2.

Thanks for the fix.

**Comment by MFernstrom** [comment]
Aha, I was wondering about that, I could have sworn it used to work.

I'll see if I can make it more intelligent, maybe add a JDK version check if I can find when then change happened.

**Comment by wua22** [comment]
Oh I wouldn't worry about that sort of check. Your fix works on older versions as it stands.

**Pull request merged**
